services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/studentdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION_MS: "86400000"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
